language: node_js
node_js:
  - node
branches:
  only: master
env:
  - EXTENSION_ID=godiecgffnchndlihlpaajjcplehddca

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
